hexapod:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    rate: 50

  tc_1_controller:
    type: effort_controllers/JointPositionController
    joint: tc_1
    pid: {p: 55, d: 0.10, i: 7562.50, i_clamp: 0.0}  #{p: 18, d: 0.15, i: 540, i_clamp: 0.0}  {p: 15, d: 0.07, i: 512.249, i_clamp: 0.0} # {p: 15.0, i: 65.0, d: 0.07, i_clamp: 0.0}  # {p: 15, d: 0.0702, i: 65.05, i_clamp: 1} # 600 # {p: 15, d: 0.07, i: 65.05, i_clamp: 1} # 700 # {p: 15, d: 0.07, i: 65.0, i_clamp: 1} # {p: 150, d: 0.07, i: 30, i_clamp: 15}

  tc_2_controller:
    type: effort_controllers/JointPositionController
    joint: tc_2
    pid: {p: 55, d: 0.10, i: 7562.50, i_clamp: 0.0} 

  tc_3_controller:
    type: effort_controllers/JointPositionController
    joint: tc_3
    pid: {p: 55, d: 0.10, i: 7562.50, i_clamp: 0.0}  

  tc_4_controller:
    type: effort_controllers/JointPositionController
    joint: tc_4
    pid: {p: 55, d: 0.10, i: 7562.50, i_clamp: 0.0}    

  tc_5_controller:
    type: effort_controllers/JointPositionController
    joint: tc_5
    pid: {p: 55, d: 0.10, i: 7562.50, i_clamp: 0.0} 

  tc_6_controller:
    type: effort_controllers/JointPositionController
    joint: tc_6
    pid: {p: 55, d: 0.10, i: 7562.50, i_clamp: 0.0} 

  ctr_1_controller:
    type: effort_controllers/JointPositionController
    joint: ctr_1
    pid: {p: 55, d: 0.10, i: 7562.50, i_clamp: 0.0}    

  ctr_2_controller:
    type: effort_controllers/JointPositionController
    joint: ctr_2
    pid: {p: 55, d: 0.10, i: 7562.50, i_clamp: 0.0} 

  ctr_3_controller:
    type: effort_controllers/JointPositionController
    joint: ctr_3
    pid: {p: 55, d: 0.10, i: 7562.50, i_clamp: 0.0} 

  ctr_4_controller:
    type: effort_controllers/JointPositionController
    joint: ctr_4
    pid: {p: 55, d: 0.10, i: 7562.50, i_clamp: 0.0} 

  ctr_5_controller:
    type: effort_controllers/JointPositionController
    joint: ctr_5
    pid: {p: 55, d: 0.10, i: 7562.50, i_clamp: 0.0}   

  ctr_6_controller:
    type: effort_controllers/JointPositionController
    joint: ctr_6
    pid: {p: 55, d: 0.10, i: 7562.50, i_clamp: 0.0} 

  fti_1_controller:
    type: effort_controllers/JointPositionController
    joint: fti_1
    pid: {p: 55, d: 0.10, i: 7562.50, i_clamp: 0.0} 

  fti_2_controller:
    type: effort_controllers/JointPositionController
    joint: fti_2
    pid: {p: 55, d: 0.10, i: 7562.50, i_clamp: 0.0} 

  fti_3_controller:
    type: effort_controllers/JointPositionController
    joint: fti_3
    pid: {p: 55, d: 0.10, i: 7562.50, i_clamp: 0.0} 

  fti_4_controller:
    type: effort_controllers/JointPositionController
    joint: fti_4
    pid: {p: 55, d: 0.10, i: 7562.50, i_clamp: 0.0} 

  fti_5_controller:
    type: effort_controllers/JointPositionController
    joint: fti_5
    pid: {p: 55, d: 0.10, i: 7562.50, i_clamp: 0.0} 

  fti_6_controller:
    type: effort_controllers/JointPositionController
    joint: fti_6
    pid: {p: 55, d: 0.10, i: 7562.50, i_clamp: 0.0} 
